### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by cheshrkat** [csstools/stylelint-value-no-unknown-custom-properties#24] opened 2022-03-23 07:32 UTC
Just wondering if maintainers could give an update on this project's status - it looks like it has been shelved, but it's always better to hear from the actual maintainers than just guess. No anger or judgement intended, it would just be good to know for sure.

(also I don't really just mean "oi is this dead" I mean it's a great time to let us know if there's something the community can do, or some factor we don't know about that's blocking things)

**Comment by Antonio-Laguna** [comment] 2022-03-23 08:21
@cheshrkat it's been shelved as with most of the repos under csstools. Jon was really prolific creating packages. We've picked the mantle but are limited to repos under [postcss-plugins](https://github.com/csstools/postcss-plugins) and cssdb for the time being.

I do, however, keep an eye on repos and pull requests but no active development is being made on them.

**Comment by ronilaukkarinen** [comment] 2022-03-23 08:41
Please see my working fork you can use (as stated [here](https://github.com/csstools/stylelint-value-no-unknown-custom-properties/pull/21#issuecomment-1064057536), got tired of waiting for the maintainer to merge my PR):

```bash
npm install @ronilaukkarinen/stylelint-value-no-unknown-custom-properties --save-dev
```

I'm going to keep it updated as we use this package in our daily life at work.

**Comment by Antonio-Laguna** [comment] 2022-03-23 08:43
@ronilaukkarinen apologies for that not being merged for so long :/ 

Do you want to get it merged? Is there anything else pending?

**Comment by ronilaukkarinen** [comment] 2022-03-23 08:49
> @ronilaukkarinen apologies for that not being merged for so long :/

No probs, I'm glad in open source makes forks possible, they come handy in plan B.

> Do you want to get it merged? Is there anything else pending?

Yes. I think currently outdated and deprecated stylelint and peerDependencies are the only things needed for this package to work. If this gets merged I can finally retire my fork and use the real deal :)

However while saying this, I think it's a good idea to go through all the other dependencies as well as there are similar PRs like #19 and #18.

PR #20 needs a review but other than that I think we're fine!

**Comment by Antonio-Laguna** [comment] 2022-03-23 09:47
@ronilaukkarinen thanks a lot :) will check this soon and get this merged & released

**Comment by Antonio-Laguna** [comment] 2022-03-23 12:05
I've merged everything, this needs some cleanup as there are usages of postcss-values-parser which we've discouraged everywhere given it's polluting the global object. See https://github.com/shellscape/postcss-values-parser/issues/143

Will keep this updated

**Comment by jameschensmith** [comment] 2022-03-23 21:09
[This line in `package.json`](https://github.com/csstools/stylelint-value-no-unknown-custom-properties/blob/930f2747a93fb67e299f19e2cb88ec66e76ca42c/package.json#L29-L30) is breaking. Must have happened when resolving merge conflicts.

**Comment by Antonio-Laguna** [comment] 2022-03-24 06:34
@jameschensmith yeah I realised pretty soon, didn't want to upset the author of the PR and I miss-merged 😂 

Right now tests aren't passing and I can't seem to figure why 2 tests aren't passing. I've tested separately with stylelint and they pass. Doesn't help that `stylelint-test-rule-tape` was written 5 years ago and is deprecated now.

If anyone has any hints or fixes that'd be ace. I'll be digging more otherwise

**Comment by jameschensmith** [comment] 2022-03-24 15:43
@Antonio-Laguna, the problem is [here](https://github.com/csstools/stylelint-value-no-unknown-custom-properties/blob/82887fd23f3e9ab37a32a674192e9612a501497b/src/lib/get-custom-properties-from-root.js#L11-L15). `let sourceDir = __dirname;` resolves to `<root>/dist` since your most recent change, and `root.source.input.file` doesn't exist, so it's trying to find the CSS test files in `./dist`. Hope this helps!

**Comment by Antonio-Laguna** [comment] 2022-03-26 21:51
Thank you all for your patience and the joined effort here! This is wonderful!

This is now released as 4.0.0!

**Closed by Antonio-Laguna** 2022-03-26 21:51 UTC

**Comment by cheshrkat** [comment] 2022-03-27 06:04
Thanks so much everyone, truly amazing :)

**Comment by ronilaukkarinen** [comment] 2022-03-27 19:27
Awesome, thank you so much!

**Comment by shellscape** [comment] 2022-07-12 15:00
> I've merged everything, this needs some cleanup as there are usages of postcss-values-parser which we've discouraged everywhere given it's polluting the global object. See [shellscape/postcss-values-parser#143](https://github.com/shellscape/postcss-values-parser/issues/143)
> 
> Will keep this updated

Point of clarification: postcss-values-parser is _not_ polluting the global namespace. It's modifying the `Container` object prototype from `postcss`. That is in fact, not the global namespace and the distinction there is important as the former could be considered derogatory. 

I think it's both dubious and unfortunate that there's a leadership recommendation away from a package given that @Antonio-Laguna themself offered to help resolve the issue. From the [issue](https://github.com/shellscape/postcss-values-parser/issues/143) itself:

```
I understand that this is not a trivial change and I'm happy to contribute time and/or to discuss anything.
```

Unfortunately, and despite that offer, there hasn't been any followup up since November 19, 2021.

Please consider being good stewards of open source and following through on offers of contribution, calling for additional help for contribution, or supporting a project financially to affect change you'd like to see.

**Comment by shellscape** [comment] 2022-07-12 16:00
> I think it's dangerous nonetheless 

Language is important. Ill-advised, sure. Dangerous? Hardly. Ended up inconvenient? Definitely. When I authored the package I never considered that people might be using it in an environment with multiple versions of postcss available to the module resolver. And so I took a risk. Turns out, it wasn't that great, and a mistake. But please don't conflate something like modifying the `String` prototype ala Prototype.js with modifying a class prototype from a package that the module resolver and cache are having a hard time with. Apples and Cauliflower comparison that is. There are inexperienced developers that will read that and take it as one in the same, without learning the why. 

> I don't have a lot of personal motivation to dive into this one.

Was entirely accurate. That's why we have donation mechanisms, to provide incentive to authors and maintainers. We have social forums like Twitter and Discord where we can call for additional help. The postcss community is vast, and `ai` is responsive and spreading calls for help, as are other community members. You did however state that you had time for discussion, which did not happen. I would have been more than wiling to discuss a fix and provide guidance as time allowed. But I understand that available time shifts (I'm a father, so I get it). I'm only highlighting that we have multiple avenues available when we hit a roadblock with open source.

It doesn't personally affect me that my package is no longer being used (if that's the case). Really, I'm not sore about it and I'm truly happy the project found a good way forward. I did chime in here because the path that was taken was not in the spirit of being good open source stewards. And that's really what is important at the end of the day to keep the ecosystem as a whole healthy.

**Comment by Antonio-Laguna** [comment] 2022-07-13 05:34
Perhaps I'm not as picky with the language and I don't get those nuances given English is my second language. I see it as a risk hence my _danger_ wording. You have the risk (in this case) of having code that doesn't produce _seemingly_ deterministic output as long as either different versions of PostCSS are used or different versions of `postcss-values-parser` are used with different outputs. If that pitfall exists, I see it as a danger, it's not the same danger as using unescaped code from the user, definitely, and I haven't implied otherwise.

> But please don't conflate something like modifying the String prototype ala Prototype.js 

I haven't conflated anything. Please avoid attributing me words and thoughts I haven't expressed myself. Is modifying the Prototype of `String` dangerous? As with almost everything in life, it depends. We have polyfills to thank for in some scenarios and those are not dangerous in nature. Abusing that in malicious ways would be dangerous though. 

>  You did however state that you had time for discussion, which did not happen. I would have been more than wiling to discuss a fix and provide guidance as time allowed. But I understand that available time shifts (I'm a father, so I get it). I'm only highlighting that we have multiple avenues available when we hit a roadblock with open source.

Could be nuances striking again but, `The package has been up and relatively stable for a number of years, so I don't have a lot of personal motivation to dive into this one.` didn't sound like a welcoming invitation for discussion to me. When I read that I decided to take another route. 

I've already apologized and I'm going to do it again. I should have been clearer and probably should have made any sort of update if the situation had changed. 

> It doesn't personally affect me that my package is no longer being used (if that's the case). Really, I'm not sore about it and I'm truly happy the project found a good way forward.

I haven't implied this either.

>  I did chime in here because the path that was taken was not in the spirit of being good open source stewards. 

I definitely meant no ill towards you or the open-source community and I apologize if that's the reading of this. I'll try to be more mindful next time.

**Comment by ronilaukkarinen** [comment] 2022-07-13 06:28
After following this discussion via my mail box I just want to chime in about what @shellscape said in this bit:

> Please consider being good stewards of open source and following through on offers of contribution

I think this statement is exactly what is <i>not</i> "being good" towards open source. Instead it is extremely condescending. If someone says they're willing to contribute their time or effort to the project or to the discussion of the project, that's kindness by itself. If it doesn't match up to your expectations, it shouldn't matter. To make people hold accountable of their willingness to help this way is just not nice.

Be kind, always be kind. This should be the number one rule of open source. Being open and kind helps this commity grow.

I have a huge admiration towards @Antonio-Laguna who has kept this dying package alive in his own terms and you're kinda bashing it. I myself have revived some old packages without having the help or even proper expertise so I get it. Instead of diminishing others in some sub-issue, always aim to help. Thank you.
